---
title: "Context stats"
output: html_document
---

# **Full context stats**

<br>
<br>
This page details the context stats that have been generated as a result of running the bamstats tool.

<br>
<br>


```{r total_context, echo=FALSE}


library(knitr)
library("RSQLite")
library("DBI")
library(stringr)
library("rmarkdown") # Make cool dynamic documents
library("knitr") # Run R Code Chunks
library("ggplot2") # For plotting
library("DT") # Interactove html tables
library(ggplot2)
library(reshape2)

setwd("./..")
mydb <- dbConnect(RSQLite::SQLite(), "csvdb")
db <- dbGetQuery(mydb, 'SELECT * FROM context_stats;')
col_idx <- grep("track", names(db))
db <- db[, c(col_idx, (1:ncol(db))[-col_idx])]

DT::datatable(as.data.frame(db, class = 'cell-border stripe'))
```

<br>

# **RNA context stats**

<br>

The following table details the context stats for RNA species:

<br>

```{r full_context_stats, echo=FALSE}


library(knitr)
library("RSQLite")
library("DBI")
library(stringr)
library("rmarkdown") # Make cool dynamic documents
library("knitr") # Run R Code Chunks
library("ggplot2") # For plotting
library("DT") # Interactove html tables
library(ggplot2)
library(reshape2)

setwd("./..")
mydb <- dbConnect(RSQLite::SQLite(), "csvdb")
db <- dbGetQuery(mydb, 'SELECT * FROM context_stats;')

db_rna <- db[,c("track",'protein_coding_gene',
                  'unclassified_noncoding_RNA','unclassified_RNA',
                  'long_noncoding_RNA','pseudogene',
                  'short_noncoding_RNA','repeats','intergenic')]

as.data.frame(db_rna, class = 'cell-border stripe')
DT::datatable(as.data.frame(db_rna, class = 'cell-border stripe'))
```

```{r venn, echo=FALSE}

db <- dbGetQuery(mydb, 'SELECT * FROM context_stats;')


db <- db[,c("track",'protein_coding_gene',
                  'unclassified_noncoding_RNA','unclassified_RNA',
                  'long_noncoding_RNA','pseudogene',
                  'short_noncoding_RNA','repeats','intergenic')]
blank_theme <- theme_minimal()+
  theme(
    axis.title.x = element_blank(),
    axis.title.y = element_blank(),
    panel.border = element_blank(),
    panel.grid=element_blank(),
    axis.ticks = element_blank(),
    plot.title=element_text(size=14, face="bold")
  )

for(i in db$track){
  row <- db[db$track == i,]
  melt <- melt(row, id.vars="track")
  pie <- ggplot(melt, aes(x="", y=value, fill=variable))+
    geom_bar(width = 1, stat = "identity")+ coord_polar("y", start=0) +  blank_theme +
    theme(axis.text.x=element_blank()) +
    scale_fill_manual(values=c("#999999", "#E69F00", "#56B4E9",
                               "#000000", "#800000", "#FCDD9D",
                               "#B55022", "#C4CDD3", "#3a7f50",
                               "#c11924", "#00ff55", "#c17b19",
                               "#00d8ff", "#090ce8", "#b29e97",
                               "#e84409", "#ff0026"))
  cat(i)
  print(pie)
}

```
