---
title: "**Exon validation**"
---

The following page details the results of running the **cgat bam_vs_gtf** script. The metrics are to look at the number of mapped and spliced reads per bam file.

The following is a table showing the full metrics from the tool:

```{r exon_validation, echo=FALSE}

library(knitr)
library("RSQLite")
library("DBI")
library(stringr)
library("rmarkdown") # Make cool dynamic documents
library("knitr") # Run R Code Chunks
library("ggplot2") # For plotting
library("DT") # Interactove html tables
library(ggplot2)
library(reshape2)

setwd("./..")
mydb <- dbConnect(RSQLite::SQLite(), "csvdb")

db <- dbGetQuery(mydb, 'SELECT * FROM exon_validation;')

db <- db[,c("track","input","mapped","spliced","spliced_bothoverlap","spliced_exact",      
            "spliced_halfoverlap","spliced_ignored","spliced_inexact","spliced_nooverlap","spliced_overrun",    
            "spliced_underrun","unmapped","unspliced","unspliced_nooverlap",
            "unspliced_nooverrun","unspliced_overlap","unspliced_overrun"  )]

DT::datatable(as.data.frame(db, class = 'cell-border stripe'))

```


# **Mapped**

```{r mapped_stats, echo=FALSE}

library(knitr)
library("RSQLite")
library("DBI")
library(stringr)
library("rmarkdown") # Make cool dynamic documents
library("knitr") # Run R Code Chunks
library("ggplot2") # For plotting
library("DT") # Interactove html tables
library(ggplot2)
library(reshape2)

setwd("./..")
mydb <- dbConnect(RSQLite::SQLite(), "csvdb")

db <- dbGetQuery(mydb, 'SELECT * FROM exon_validation;')

db <- db[,c("track","unmapped","mapped")]


blank_theme <- theme_minimal()+
  theme(
    axis.title.x = element_blank(),
    axis.title.y = element_blank(),
    panel.border = element_blank(),
    panel.grid=element_blank(),
    axis.ticks = element_blank(),
    plot.title=element_text(size=14, face="bold")
  )

for(i in db$track){
  row <- db[db$track == i,]
  melt <- melt(row, id.vars="track")
  pie <- ggplot(melt, aes(x="", y=value, fill=variable))+
    geom_bar(width = 1, stat = "identity")+ coord_polar("y", start=0) +  blank_theme +
    theme(axis.text.x=element_blank()) +
    scale_fill_manual(values=c("#999999", "#E69F00", "#56B4E9",
                               "#000000", "#800000", "#FCDD9D",
                               "#B55022", "#C4CDD3", "#3a7f50",
                               "#c11924", "#00ff55", "#c17b19",
                               "#00d8ff", "#090ce8", "#b29e97",
                               "#e84409", "#ff0026"))
  cat(i)
  print(pie)
}

```



# **Spliced**


```{r spliced_stats, echo=FALSE}

library(knitr)
library("RSQLite")
library("DBI")
library(stringr)
library("rmarkdown") # Make cool dynamic documents
library("knitr") # Run R Code Chunks
library("ggplot2") # For plotting
library("DT") # Interactove html tables
library(ggplot2)
library(reshape2)

setwd("./..")
mydb <- dbConnect(RSQLite::SQLite(), "csvdb")

db <- dbGetQuery(mydb, 'SELECT * FROM exon_validation;')

db <- db[,c("track","unspliced","spliced")]


blank_theme <- theme_minimal()+
  theme(
    axis.title.x = element_blank(),
    axis.title.y = element_blank(),
    panel.border = element_blank(),
    panel.grid=element_blank(),
    axis.ticks = element_blank(),
    plot.title=element_text(size=14, face="bold")
  )

for(i in db$track){
  row <- db[db$track == i,]
  melt <- melt(row, id.vars="track")
  pie <- ggplot(melt, aes(x="", y=value, fill=variable))+
    geom_bar(width = 1, stat = "identity")+ coord_polar("y", start=0) +  blank_theme +
    theme(axis.text.x=element_blank()) +
    scale_fill_manual(values=c("#999999", "#E69F00", "#56B4E9",
                               "#000000", "#800000", "#FCDD9D",
                               "#B55022", "#C4CDD3", "#3a7f50",
                               "#c11924", "#00ff55", "#c17b19",
                               "#00d8ff", "#090ce8", "#b29e97",
                               "#e84409", "#ff0026"))
  cat(i)
  print(pie)
}

```